language: c
os:
  - linux
  - osx
  - windows
env:
  - PYTHON_VERSION=3.5 NPY_PIN_VERSION="=1.15"
  - PYTHON_VERSION=3.7
jobs:
  include:
    - env: PYTHON_VERSION=3.7 SYSTEMGFORTRAN=1
      sudo: required
before_install:
  - export NPY_DISTUTILS_APPEND_FLAGS=1
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  - conda config --add channels conda-forge
  - if [[ $DOCS != 1 ]]; then
      DEP="pytest-cov";
    else
      DEP="sphinx sphinx_rtd_theme";
    fi
  - if [[ $SYSTEMGFORTRAN != 1 ]]; then
      GFORTRAN="fortran-compiler";
    else
      sudo apt-get install gfortran;
    fi
  - conda create -q -n testenv
      python=$PYTHON_VERSION obspy $GFORTRAN "numpy$NPY_PIN_VERSION" $DEP
  - conda activate testenv
  - conda list
  - find . -name lapack\*
install:
  - pip install -v --no-deps .
script:
  - if [[ $DOCS != 1 ]]; then
      mkdir empty; cd empty; pytest -v --cov=telewavesim --pyargs telewavesim;
    else
      cd docs; make html; touch _build/html/.nojekyll; cd ..;
    fi
after_success:
  - if [[ $DOCS != 1 ]]; then
      bash <(curl -s https://codecov.io/bash);
    else
      openssl aes-256-cbc -K $encrypted_4b1a607b6302_key -iv $encrypted_4b1a607b6302_iv -in ".travis/github_deploy_key.enc" -out ".travis/github_deploy_key" -d;
    fi
notifications:
    email: false
deploy:
  provider: pages:git
  edge: true # opt in to dpl v2
  deploy_key: .travis/github_deploy_key
  local_dir: docs/_build/html
  on:
    condition: $DOCS = 1
